version: "3.8"
services:
  devcontainer:
    command: sleep infinity
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - .env
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres-data: {}
